server:
  port: 8085


spring:
  datasource:
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      # 基本属性 url、user、password
      url: jdbc:oracle:thin:@106.54.14.206:1521/orcl
      username: XMPT
      password: XMPT
      # 配置初始化大小、最小、最大 (通常来说，只需要修改initialSize、minIdle、maxActive)
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis:  60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #第一次连接数据库时会发送该连接，导致异常。注释就好了
      #validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
  main:
    #解决springboot版本的bean无法覆盖问题
    allow-bean-definition-overriding: true

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: hrh423...
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000

#mybatis
mybatis-plus:
  #指定mapper.xml的位置
  mapper-locations: classpath*:/mapper/**Mapper.xml

# 指定logback日志的配置文件
logging:
  config: classpath:logback-custom.xml
